
INSERT INTO ROOMS (ROOMID, NAME, DESCRIPTION)
VALUES (ROOMS_SEQ.nextval , 'Start Room','Starting room');

INSERT INTO ROOMS (ROOMID, NAME, DESCRIPTION)
VALUES (ROOMS_SEQ.nextval , 'Davis 115','Room 115 in the Davis building');

INSERT INTO ROOMS (ROOMID, NAME, DESCRIPTION)
VALUES (ROOMS_SEQ.nextval , 'Davis 225','Room 225 in the Davis building');

INSERT INTO ROOMS (ROOMID, NAME, DESCRIPTION)
VALUES (ROOMS_SEQ.nextval , 'Dalton','food court in the Dalton buiding');

INSERT INTO ROOMS (ROOMID, NAME, DESCRIPTION)
VALUES (ROOMS_SEQ.nextval , 'CR 142','Room CR 142');

INSERT INTO ROOMS (ROOMID, NAME, DESCRIPTION)
VALUES (ROOMS_SEQ.nextval , 'End room','The End room');



INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Start Room'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 115')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Start Room'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 225')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Start Room'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'CR 142')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Start Room'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Dalton')
       );


INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 115'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Start Room')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 115'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 225')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 115'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'CR 142')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 115'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'End room')
       );


INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 225'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Start Room')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 225'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 115')
       );






INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Dalton'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Start Room')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Dalton'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'CR 142')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'Dalton'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'End room')
       );







INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'CR 142'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Start Room')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'CR 142'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 115')
       );
INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'CR 142'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Dalton')
       );




INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'End room'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Davis 115')
       );

INSERT INTO CONNECTIONS (ROOM1, ROOM2)
VALUES (
        (Select ROOMID FROM ROOMS WHERE NAME = 'End room'),
        (Select ROOMID FROM ROOMS WHERE NAME = 'Dalton')
       );


commit;